name: dt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7* 
  - pip=20.3.4               # Ensure pip version is compatible
  - numpy=1.20.1             # Compatible numpy for Python 3.7
  - tqdm=4.59.0
  - tensorboardX=2.1
  - cython<0.30              # Keep: Crucial for mujoco-py 2.0.2.8 compilation
  - wheel                    # Keep: Crucial for building wheels
  - patchelf                 # Keep: For patching binaries, helpful for some envs
  - intel-openmp
  - pip:
    - gym==0.17.3
    - mujoco-py==2.0.2.8     # <--- CRITICAL: Use mujoco-py 2.0.2.8 for Python 3.7 compatibility
    - transformers==4.10.0
    - wandb==0.9.1
    - glfw==1.12.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - opencv-python==4.5.1.48
    - scikit-image
    - moviepy==1.0.3
    - pybullet==3.1.7
    - dotmap==1.3.25
    - gym-notices==0.0.8
    - einops==0.3.0
# prefix: /home/$USER/anaconda3/envs/dt
